name: Release-Build-Pack-Master

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test --configuration Release --results-directory artifacts --logger trx;logfilename=TEST.xml

    - name: Pack
      run: dotnet pack /p:Configuration=release --output artifacts --verbosity Detailed

    - name: Publish Artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: Alexa.NET/artifacts

    - name: NuGet
      uses: timheuer/nuget-tool-installer@releases/v0.1
      with:
        nuget-version: '>=5.1.0'

